
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "KVBServerService", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:8080/keyValueBase/KVBServer?wsdl")
public class KVBServerService
    extends Service
{

    private final static URL KVBSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservices.KVBServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservices.KVBServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/keyValueBase/KVBServer?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/keyValueBase/KVBServer?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        KVBSERVERSERVICE_WSDL_LOCATION = url;
    }

    public KVBServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KVBServerService() {
        super(KVBSERVERSERVICE_WSDL_LOCATION, new QName("http://webServices/", "KVBServerService"));
    }

    /**
     * 
     * @return
     *     returns KVBServer
     */
    @WebEndpoint(name = "KVBServerPort")
    public KVBServer getKVBServerPort() {
        return super.getPort(new QName("http://webServices/", "KVBServerPort"), KVBServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KVBServer
     */
    @WebEndpoint(name = "KVBServerPort")
    public KVBServer getKVBServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "KVBServerPort"), KVBServer.class, features);
    }

}
