
package webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "KVBServer", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KVBServer {


    /**
     * 
     * @param arg0
     * @throws ServiceInitializingException_Exception
     * @throws FileNotFoundException_Exception
     * @throws ServiceAlreadyInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webServices/", className = "webservices.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webServices/", className = "webservices.InitResponse")
    public void init(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception, ServiceAlreadyInitializedException_Exception, ServiceInitializingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://webServices/", className = "webservices.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webServices/", className = "webservices.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws KeyAlreadyPresentException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://webServices/", className = "webservices.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://webServices/", className = "webservices.InsertResponse")
    public void insert(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyAlreadyPresentException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ValueListImpl
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://webServices/", className = "webservices.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://webServices/", className = "webservices.ReadResponse")
    public ValueListImpl read(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://webServices/", className = "webservices.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://webServices/", className = "webservices.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<webservices.ValueListImpl>
     * @throws BeginGreaterThanEndException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scan", targetNamespace = "http://webServices/", className = "webservices.Scan")
    @ResponseWrapper(localName = "scanResponse", targetNamespace = "http://webServices/", className = "webservices.ScanResponse")
    public List<ValueListImpl> scan(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        KeyImpl arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

}
